version: '3.8'
services:
  api:
    image: real-estate-api-demo
    ports:
      - 3000:3000
    container_name: real-estate-api-demo-container
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - GCLOUD_API_KEY=${GCLOUD_API_KEY}
      - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
      - ALGOLIA_ADMIN_API_KEY=${ALGOLIA_ADMIN_API_KEY}
      - CLOUDAMQP_URL=${CLOUDAMQP_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - AXIOM_API_TOKEN=${AXIOM_API_TOKEN}
