const features = [
  'Rent-to-Own',
  'Corner Unit',
  'Penthouse Unit',
  'Dishwasher',
  'Laundry - In Suite',
  'Laundry - Coin / Card',
  'Laundry - Shared',
  'In-Suite Storage',
  'Storage Lockers',
  'Ocean Views',
  'City Views',
  'Mountain Views',
  'River Views',
  'Air Conditioning',
  'Fireplace',
  'Jetted Tub / Jacuzzi',
  'Hardwood Floors',
  'Laminate Floors',
  'Swinming Pool',
  'Fitness Ares',
  'Elevator',
  'Zero-Step Entrance',
  'Extra-Wide Doorways',
  'Roll-In Shower',
  'Tile Flooring',
  'Luxury Vinyl Plank Flooring',
  'Balcony',
  'Fenced Backyard',
  'Fire Pit',
  'Lake Access',
];

export default features;
